In [1]:



import numpy as np
x1,y1=5,5
xp1,yp1=100,100
x2,y2=150,5
xp2,yp2=200,80
x3,y3=150,150
xp3,yp3=220,80
x4,y4=5,150
xp4,yp4=100,200



In [2]:
A=np.array([[-x1,-y1,-1,0,0,0,x1*xp1,y1*xp1,xp1],
          [0,0,0,-x1,-y1,-1,x1*yp1,y1*yp1,yp1],
          [-x2,-y2,-1,0,0,0,x2*xp2,y2*xp2,xp2],
          [0,0,0,-x2,-y2,-1,x2*yp2,y2*yp2,yp2],
          [-x3,-y3,-1,0,0,0,x3*xp3,y3*xp3,xp3],
          [0,0,0,-x3,-y3,-1,x3*yp3,y3*yp3,yp3],
          [-x4,-y4,-1,0,0,0,x4*xp4,y4*xp4,xp4],
           [0,0,0,-x4,-y4,-1,x4*yp4,y4*yp4,yp4]])
A

array([[   -5,    -5,    -1,     0,     0,     0,   500,   500,   100],
       [    0,     0,     0,    -5,    -5,    -1,   500,   500,   100],
       [ -150,    -5,    -1,     0,     0,     0, 30000,  1000,   200],
       [    0,     0,     0,  -150,    -5,    -1, 12000,   400,    80],
       [ -150,  -150,    -1,     0,     0,     0, 33000, 33000,   220],
       [    0,     0,     0,  -150,  -150,    -1, 12000, 12000,    80],
       [   -5,  -150,    -1,     0,     0,     0,   500, 15000,   100],
       [    0,     0,     0,    -5,  -150,    -1,  1000, 30000,   200]])

In [3]:
At=A.transpose()
RA=np.dot(At,A)
RA.shape
A.shape
At.shape

(9, 8)

In [4]:
from numpy import linalg as LA

In [5]:
w, v = LA.eig(RA)

In [6]:
w

array([ 3.62583363e+09,  1.01280011e+09,  6.80651927e+04,  3.46776193e+04,
        2.12012335e+04,  3.70648899e+03,  1.52001454e+01,  6.56490976e-01,
       -1.66509311e-10])

In [7]:
v

array([[ 2.84043894e-03,  3.14430147e-03, -2.46384735e-01,
        -1.58554932e-01, -1.75245114e-01,  1.76705635e-01,
         9.13738625e-01, -1.20261073e-01,  5.31056349e-02],
       [ 2.42121739e-03, -1.28321626e-03, -3.77000733e-01,
         1.76600215e-01,  6.89508147e-01,  5.90273326e-01,
        -5.29344506e-02, -2.23230961e-03, -4.91718842e-03],
       [ 2.20891154e-05,  1.13495064e-05, -2.37217168e-03,
        -3.65660431e-03,  5.19584361e-03,  7.52000216e-03,
         6.59901593e-02,  7.85970681e-01,  6.14648552e-01],
       [ 1.09109680e-03,  1.17416448e-03,  6.61240940e-01,
         3.41172744e-01,  5.01749740e-01, -2.32499365e-01,
         3.72052358e-01, -4.25903577e-02,  1.77018783e-02],
       [ 1.63479471e-03, -2.90636016e-03,  5.74279813e-01,
        -7.10405325e-02, -3.14549320e-01,  7.49883366e-01,
        -6.19835401e-02,  4.58785877e-03, -3.93375074e-03],
       [ 1.33908907e-05, -1.14077892e-05,  5.80190908e-03,
        -2.15181510e-03,  2.88147957e-03, -5.735047

In [8]:
i=np.argmin(w)

In [106]:
w[8]

-1.6650931116702573e-10

In [107]:
v.shape

(9, 9)

In [110]:
X=v[:,i]

In [9]:
np.dot(A,X)

NameError: name 'X' is not defined