In [1]:
import numpy as np
from numpy import linalg 
x1,y1=5,5
xp1,yp1=100,100
x2,y2=150,5
xp2,yp2=200,80
x3,y3=150,150
xp3,yp3=220,80
x4,y4=5,150
xp4,yp4=100,200
A=np.array([[-x1,-y1,-1,0,0,0,x1*xp1,y1*xp1,xp1],
          [0,0,0,-x1,-y1,-1,x1*yp1,y1*yp1,yp1],
          [-x2,-y2,-1,0,0,0,x2*xp2,y2*xp2,xp2],
          [0,0,0,-x2,-y2,-1,x2*yp2,y2*yp2,yp2],
          [-x3,-y3,-1,0,0,0,x3*xp3,y3*xp3,xp3],
          [0,0,0,-x3,-y3,-1,x3*yp3,y3*yp3,yp3],
          [-x4,-y4,-1,0,0,0,x4*xp4,y4*xp4,xp4],
          [0,0,0,-x4,-y4,-1,x4*yp4,y4*yp4,yp4]])
# A is 8*9
A

array([[   -5,    -5,    -1,     0,     0,     0,   500,   500,   100],
       [    0,     0,     0,    -5,    -5,    -1,   500,   500,   100],
       [ -150,    -5,    -1,     0,     0,     0, 30000,  1000,   200],
       [    0,     0,     0,  -150,    -5,    -1, 12000,   400,    80],
       [ -150,  -150,    -1,     0,     0,     0, 33000, 33000,   220],
       [    0,     0,     0,  -150,  -150,    -1, 12000, 12000,    80],
       [   -5,  -150,    -1,     0,     0,     0,   500, 15000,   100],
       [    0,     0,     0,    -5,  -150,    -1,  1000, 30000,   200]])

In [22]:
RA=np.matmul(A.transpose(),A)#right singular vectors 9*9(V)
LA=np.matmul(A,A.transpose())#left singular vectors 8*8(U)
w1, v1 = linalg.eig(RA)
#Sorting the eig values and vectors in descending order
w1 = w1[w1.argsort()[::-1]]
v1=v1[w1.argsort()[::-1]]

w2, v2 = linalg.eig(LA)
w2 = w2[w2.argsort()[::-1]]
v2=v2[w2.argsort()[::-1]]
H=np.reshape(v1[:,8],(3,3))#Homography matrix
H


array([[ 3.50321685e-03,  3.37762918e-03, -8.13642090e-01],
       [-2.55301166e-03, -2.92733046e-03,  5.81332763e-01],
       [-3.66202493e-07, -2.00680613e-06,  9.16829699e-06]])

In [5]:
np.dot(A,v1[:,8])

array([ 0.77896818, -0.55420073,  0.26011219, -0.18820805, -0.29477707,
        0.21297591,  0.26011327, -0.18820486])

In [16]:
import numpy as np
from numpy import linalg 
x1,y1=5,5
xp1,yp1=100,100
x2,y2=150,5
xp2,yp2=200,80
x3,y3=150,150
xp3,yp3=220,80
x4,y4=5,150
xp4,yp4=100,200
A=np.array([[-x1,-y1,-1,0,0,0,x1*xp1,y1*xp1,xp1],
          [0,0,0,-x1,-y1,-1,x1*yp1,y1*yp1,yp1],
          [-x2,-y2,-1,0,0,0,x2*xp2,y2*xp2,xp2],
          [0,0,0,-x2,-y2,-1,x2*yp2,y2*yp2,yp2],
          [-x3,-y3,-1,0,0,0,x3*xp3,y3*xp3,xp3],
          [0,0,0,-x3,-y3,-1,x3*yp3,y3*yp3,yp3],
          [-x4,-y4,-1,0,0,0,x4*xp4,y4*xp4,xp4],
          [0,0,0,-x4,-y4,-1,x4*yp4,y4*yp4,yp4]])
# A is 8*9

RA=np.matmul(A.transpose(),A)#right singular vectors 9*9(V)
LA=np.matmul(A,A.transpose())#leftt singular vectors 8*8(U)
w1, v1 = linalg.eig(RA)
#Sorting the eig values and vectors in descending order
w1 = w1[w1.argsort()[::-1]]
v1=v1[w1.argsort()[::-1]]

w2, v2 = linalg.eig(LA)
w2 = w2[w2.argsort()[::-1]]
v2=v2[w2.argsort()[::-1]]
H=np.reshape(v1[:,8],(3,3))#Homography matrix

In [17]:
H

array([[ 3.50321685e-03,  3.37762918e-03, -8.13642090e-01],
       [-2.55301166e-03, -2.92733046e-03,  5.81332763e-01],
       [-3.66202493e-07, -2.00680613e-06,  9.16829699e-06]])

In [18]:
# A=UDV'
#A is 8*9
# U is 8*8 right singular vectors
# D is 8*9 diagonal matrix 
# V is 9*9 left singular vectors
U=v2
#V=v1.transpose()
V=v1
D=np.diag(np.sqrt(w2))
D=np.concatenate((D,np.zeros((8,1))), axis=1)


D:\AnacondaPython\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([[4.67160061e+04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 3.18041265e+04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.21610417e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.47084206e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.36318729e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.72298815e+01, 0.00000000e+00, 0.00000000e+00,
        0.0

In [19]:
w2

array([ 2.18238522e+09,  1.01150246e+09,  4.91111768e+04,  2.16337636e+04,
        1.85827958e+04,  2.23066171e+03,  4.57099977e+00, -2.85018513e+09])

In [20]:
w1

array([ 1.31952413e+06,  7.03096407e+04,  2.68500021e+04,  2.55786588e+04,
        8.43240829e+03,  1.23446978e+00,  1.01580774e-01, -6.70428391e+08,
       -3.28219549e+09])